server:
  port: 8081
spring:
  application:
    name: kittybank
  profiles:
#    Uncomment the line below to use local config, comment when push/pull
#   active: local
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/kitty_bank
    username: root
    password: kitty123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect